name: FetchAccessToken_build_test

on:
  push:
    branches-ignore:    
      - main
    paths:
      - 'Frends.ServiceNow.FetchAccessToken/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.ServiceNow.FetchAccessToken
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
